### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ehab09** [PietroMSB/DrugSideEffects#3]
Dear Pietro,

How can I install the library "tensorflow.keras.models" knowing that the library "tensorflow" is already installed?
https://github.com/PietroMSB/DrugSideEffects/blame/56a7dafad4a757cab6f35c1c1eb5660092e10cc9/graphsage_node_classifier.py#L20

In file
 -> graphsage_node_classifier.py

There is also a similar one in the file -> spektral_node_classifier.py.

Best,
Ehab09

**Comment by PietroMSB** [comment]
Dear Ehab09,

You don't need to install subpackages: when any package is installed, you can import any of its subpackages and their children at any level of the hierarchy. For instance, if you installed _tensorflow_ you should be able to either _import tensorflow as tf_, _import tensorflow_, _import tensorflow.keras_, import _tensorflow.keras.models_ and so on.
If you have issues importing subpackages you might need a different version of tensorflow, or maybe just try using _tensorflow.compat.v1_ instead of _tensorflow_
Let me know if everything works fine,

Best,
Pietro

**Comment by Ehab09** [comment]
Dear Pietro,

Thank you very much my dear friend for helping me.

I am working on the project... Is there a research paper or something similar to show the steps of the project?
I will be grateful to you.

Best,
Ehab09

**Comment by PietroMSB** [comment]
Dear Ehab09,

Sure, you can find our paper here: https://ieeexplore.ieee.org/abstract/document/9775571

Thank you very much for asking: only now I noticed that I didn't add the paper to the project's description (I am adding it now)

Best,
Pietro
